# Generated by Django 5.2.6 on 2026-01-31 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=90, unique=True)),
                ('ip', models.CharField(max_length=120, unique=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
    ]
