# Generated by Django 5.2.6 on 2026-01-31 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hub', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pdg', 'Pending'), ('cnf', 'Confirmed'), ('iqu', 'In Queue'), ('acd', 'Awaiting Customer Decision'), ('ort', 'On Route'), ('cmp', 'Completed'), ('rej', 'Rejected')], default='pdg', max_length=3)),
                ('sku', models.CharField(max_length=7)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('operation', models.SmallIntegerField(blank=True, choices=[(0, 'Confirm Current Batch Quantity'), (1, 'Wait For Requested Batch Quantity')], null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hub.cd')),
            ],
        ),
    ]
